# Dependencies
markdown:         redcarpet
redcarpet:
 extensions: ["footnotes", "tables", "lax_spacing"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            jhbraun
tagline:          
url:              http://www.jhbraun.com
paginate:         5
baseurl:          /
author:
  name:           Jordan H Braun
  url:            https://twitter.com/designjordan
  email:          jordan@jhbraun.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
