# Site settings
title: jhbraun
email: jordan@jhbraun.com
description: > # this means to ignore newlines until "baseurl:"
  The musings and wild rants of Jordan Braun. Mostly blog posts on design and some samples of his work.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jhbraun.com" # the base hostname & protocol for your site
twitter_username: DESIGNJORDAN
github_username:  jordanhbraun

# Build settings
markdown: kramdown

collections:
- work

collections:
 work:
  output: true


flickr:
  screen_name: designjordan
  api_key: 1ce96dda269d873c742306b05625be6c
  api_secret: 4322416cd571dad4
